name: PetClinic CI Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          ./mvnw test

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Build Tag and push Docker Image
        env:
          IMAGE_NAME: jmk.jfrog.io/docker/spring-petclinic:${{ github.run_number }}
        run: |
          jfrog rt docker-build --build-name=jmk-petclinic-build --build-number=${{ github.run_number }} --image-name=$IMAGE_NAME .

      - name: Publish Build info With JFrog CLI
        env:
          JFROG_CLI_BUILD_NAME: jmk-petclinic-build
          JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
        run: |
          jfrog rt build-collect-env
          jfrog rt build-add-git
          jfrog rt build-publish
