name: PetClinic CI Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      #- name: Run Tests
      #  run: |
      #    ./mvnw test

      - name: Build Container Image with Spring Boot Maven plugin
        run: |
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=jmk.jfrog.io/docker/jmk-spring-petclinic:${{ github.run_number }}

      - name: Push Docker Image
        run: | 
          jfrog docker push jmk.jfrog.io/docker/jmk-spring-petclinic:${{ github.run_number }}

      - name: Trigger Xray Scan
        run: |
          jfrog xr scanschedule-start --build-name=jmk-petclinic-build --build-number=${{ github.run_number }} jmk.jfrog.io/docker/jmk-spring-petclinic:${{ github.run_number }}

      - name: Publish Build info With JFrog CLI
        env:
          JFROG_CLI_BUILD_NAME: jmk-petclinic-build
          JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
        run: |
          jfrog rt build-collect-env
          jfrog rt build-add-git
          jfrog rt build-publish

      
