name: Build and Publish Docker Image for Spring-PetClinic

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Compile Code
        run: |
          ./mvnw compile

      - name: Run Tests
        run: |
          ./mvnw test

      - name: Package Project As Docker Image
        run: |
          docker build -t spring-petclinic .

      - name: Log In To JFrog Artifactory
        run: |
          docker login -u ${{ secrets.ARTIFACTORY_USERNAME }} -p ${{ secrets.ARTIFACTORY_PASSWORD }} your-artifactory-url

      - name: Publish Docker image to Artifactory
        run: |
          docker tag spring-petclinic your-artifactory-url/repository/spring-petclinic:${{ github.run_number }}
          docker push your-artifactory-url/repository/spring-petclinic:${{ github.run_number }}
